### ISSUE TITLE
S04 of Omega's Tale ("Slaves") is broken

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/The_War_of_Terrador#4]
it ends in defeat immediately upon start, because for some reason Omega isn't created? I dunno why...

**Comment by knyghtmare** [comment]
I'd just leave this for later for focus on getting the main TWoT campaign fully functional. The prequel can wait.

**Comment by cooljeanius** [comment]
ok fair

**Comment by cooljeanius** [comment]
ok I fixed the end-in-defeat bug in c90888d thanks to vghetto on the forums!

**Comment by cooljeanius** [comment]
> ok I fixed the end-in-defeat bug in [c90888d](https://github.com/cooljeanius/The_War_of_Terrador/commit/c90888d3089038c5bacc7cdda2a1a922e97632e8) thanks to vghetto's [post](https://forums.wesnoth.org/viewtopic.php?p=667898#p667898) on the forums!

Do you think it's worth doing a new release on the 1.14 add-on server just for this change, or should I wait and save it for a larger release on the 1.16 add-on server? I'm leaning towards the latter...
