### ISSUE TITLE
[TWoT] Era advert and non-existent feedback link in campaign description

### ISSUE THREAD

**Issue by knyghtmare** [cooljeanius/The_War_of_Terrador#5]
https://github.com/cooljeanius/The_War_of_Terrador/blob/32f9b1d50a1cf3e7e406a5cc018f77a7643978a4/_main.cfg#L29-L30

**Comment by cooljeanius** [comment]
the link works for me; it just redirects here: https://tkta.rpg-board.net/ 
Board seems pretty dead, though... should I just remove it?

**Comment by cooljeanius** [comment]
is c03079e acceptable?

**Comment by knyghtmare** [comment]
> the link works for me; it just redirects here: https://tkta.rpg-board.net/
> Board seems pretty dead, though... should I just remove it?

I would just replace with the Wesnoth forum link of the TWoT topic. This DragonChampion's forum looks pretty dead.

**Comment by cooljeanius** [comment]
> 
> I would just replace with the Wesnoth forum link of the TWoT topic. This DragonChampion's forum looks pretty dead.

ok how about 624ecb8 then?

**Comment by cooljeanius** [comment]
Closing this now.
