### ISSUE TITLE
[TWoT] custom "snipe" range needs an icon

### ISSUE THREAD

**Issue by knyghtmare** [cooljeanius/The_War_of_Terrador#6]
It keeps showing as `UNTLB range_snipe`

**Comment by cooljeanius** [comment]
This is pretty minor

**Comment by cooljeanius** [comment]
> It keeps showing as `UNTLB range_snipe`

Commit d7d97c5 ought to fix the display of the name of the range; it still needs an icon for it, though

**Comment by cooljeanius** [comment]
> > It keeps showing as `UNTLB range_snipe`
> 
> Commit [d7d97c5](https://github.com/cooljeanius/The_War_of_Terrador/commit/d7d97c52a56f9f934b4a19d8ad903852fce3791c) ought to fix the display of the name of the range; it still needs an icon for it, though

d7d97c5 made it into [1.4.1](https://github.com/cooljeanius/The_War_of_Terrador/releases/tag/1.4.1); finding an icon for it will have to wait until a post-BfW-1.16 release, though...

**Comment by cooljeanius** [comment]
retitled

**Comment by cooljeanius** [comment]
@knyghtmare sent me this on Discord to use as an icon:
![range_snipe](https://user-images.githubusercontent.com/1388660/169357444-5cb26755-48c1-4f1e-a241-e8959c749231.png)

**Comment by cooljeanius** [comment]
ok [962e845](https://github.com/cooljeanius/The_War_of_Terrador/commit/962e8455902d8f74060facf6280723eef5145465) seems to fix this for me; I'm not going to cut an entire new release just for a single new icon though...

**Comment by cooljeanius** [comment]
> ok [962e845](https://github.com/cooljeanius/The_War_of_Terrador/commit/962e8455902d8f74060facf6280723eef5145465) seems to fix this for me; I'm not going to cut an entire new release just for a single new icon though...

@knyghtmare give me something else to change so I can have enough to feel like it's worth cutting a new release
