### ISSUE TITLE
[TWoT] Some villages are not visible on the map

### ISSUE THREAD

**Issue by knyghtmare** [cooljeanius/The_War_of_Terrador#7]
I have just played through S1 and I see there are some 17 villages, however the map only shows me like 10. 7 villages are missing some image.

**Comment by cooljeanius** [comment]
oh yeah I was considering this to be part of bug #2

**Comment by cooljeanius** [comment]
closing as a dup of bug #2

**Comment by cooljeanius** [comment]
copying my question from issue #2 (please reply there): would it be acceptable to give up on trying to get the animations to work if just a single still image works instead?

**Comment by cooljeanius** [comment]
never mind; fixed with 9ef7626
