### ISSUE TITLE
[TWoT] Xylash Quickbred has an incorrect advancement

### ISSUE THREAD

**Issue by knyghtmare** [cooljeanius/The_War_of_Terrador#8]
https://github.com/cooljeanius/The_War_of_Terrador/blob/32f9b1d50a1cf3e7e406a5cc018f77a7643978a4/units/Xylash_Quickbred.cfg#L14

Should be `Xfighter` and not `Fighter`

The add-on looks like a buggy mess.

**Comment by cooljeanius** [comment]
> 
> The add-on looks like a buggy mess.

I mean, yeah, I agree, but you asked me to port it, so...

**Comment by cooljeanius** [comment]
should be done by 18b76e7; can you confirm?

**Comment by knyghtmare** [comment]
> should be done by [18b76e7](https://github.com/cooljeanius/The_War_of_Terrador/commit/18b76e7f30d6c045b4fdc5b05462d4553aee4c5e); can you confirm?

looks like alright now

> > The add-on looks like a buggy mess.
> 
> I mean, yeah, I agree, but you asked me to port it, so...

It wasn't a mess that time :O

**Comment by cooljeanius** [comment]
> > should be done by [18b76e7](https://github.com/cooljeanius/The_War_of_Terrador/commit/18b76e7f30d6c045b4fdc5b05462d4553aee4c5e); can you confirm?
> 
> looks like alright now
> 

OK, closing.

> > > The add-on looks like a buggy mess.
> > 
> > 
> > I mean, yeah, I agree, but you asked me to port it, so...
> 
> It wasn't a mess that time :O

You sure that's not just nostalgia-glasses? I can't think of anything I did that would have broken it; you either must have just never noticed it previously, or it must be inherent to the porting process between 1.8 and 1.14...

**Comment by cooljeanius** [comment]
I think on Discord you mentioned this affecting another unit? Can you remind me which?

**Comment by cooljeanius** [comment]
ok I see it in `u.w.o`: https://units.wesnoth.org/1.14/The_War_of_Terrador/en_US/War_of_Terrador.html

**Comment by cooljeanius** [comment]
@knyghtmare can you verify that 5692c16 fixes this? Also is it worth doing a new minor point release just for this and the fix to bug #4?

**Comment by cooljeanius** [comment]
OK I think it's fixed this time; will save a new release for post-1.16.
